/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Article: typeof import('./src/components/article/index.vue')['default']
    Bar: typeof import('./src/components/loading/bar.vue')['default']
    BgRender: typeof import('./src/components/music/bgRender.vue')['default']
    Box: typeof import('./src/components/music/box/index.vue')['default']
    Btn: typeof import('./src/components/btn/index.vue')['default']
    Chart: typeof import('./src/components/chart/index.vue')['default']
    Copyright: typeof import('./src/components/article/copyright.vue')['default']
    Directory: typeof import('./src/components/menu/directory.vue')['default']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    LyricPlayer: typeof import('./src/components/music/lyricPlayer.vue')['default']
    Modal: typeof import('./src/components/modalBox/modal.vue')['default']
    Music: typeof import('./src/components/music/index.vue')['default']
    Nav: typeof import('./src/components/nav/index.vue')['default']
    PageHeader: typeof import('./src/components/header/pageHeader.vue')['default']
    Pagination: typeof import('./src/components/pagination/index.vue')['default']
    Rbtn: typeof import('./src/components/btn/rbtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarMenu: typeof import('./src/components/menu/sidebarMenu.vue')['default']
    Tabs: typeof import('./src/components/tabs/index.vue')['default']
    Theme: typeof import('./src/components/btn/theme/index.vue')['default']
    User: typeof import('./src/components/user/index.vue')['default']
  }
}
