/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Article: typeof import('./src/components/article/index.vue')['default']
    Bar: typeof import('./src/components/loading/bar.vue')['default']
    Baring: typeof import('./src/components/loading/baring.vue')['default']
    Btn: typeof import('./src/components/btn/index.vue')['default']
    Copyright: typeof import('./src/components/article/copyright.vue')['default']
    Datile: typeof import('./src/components/article/datile.vue')['default']
    Details: typeof import('./src/components/article/details.vue')['default']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    MsgPrompt: typeof import('./src/components/global/msg-prompt/index.vue')['default']
    Music: typeof import('./src/components/music/index.vue')['default']
    Nav: typeof import('./src/components/nav/index.vue')['default']
    PageHeader: typeof import('./src/components/header/pageHeader.vue')['default']
    Rbtn: typeof import('./src/components/btn/rbtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabs: typeof import('./src/components/tabs/index.vue')['default']
    Theme: typeof import('./src/components/btn/theme/index.vue')['default']
    User: typeof import('./src/components/user/index.vue')['default']
  }
}
